# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

HAILO_APPS_CORE_GSTREAMER += "${LAYERDIR}/recipes-gstreamer/*/*.bb \
                              ${LAYERDIR}/recipes-gstreamer/*/*.bbappend "

BBFILES += " ${@bb.utils.contains('BBFILE_COLLECTIONS', 'meta-hailo-apps-core', '${HAILO_APPS_CORE_GSTREAMER}', '', d)}"

LICENSE_PATH = "${LAYERDIR}/licenses/"
BBFILE_COLLECTIONS += "meta-hailo-apps-core-internals"
BBFILE_PATTERN_meta-hailo-apps-core-internals = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-hailo-apps-core-internals = "9"

LAYERDEPENDS_meta-hailo-apps-core-internals = "core"
LAYERSERIES_COMPAT_meta-hailo-apps-core-internals = "scarthgap"

HW_ARCH = "hailo8"
